# Site
name: "Everglades Law Center"
title: "Everglades Law Center"
description: "The Everglades Law Center is a nonprofit law firm dedicated to representing the public interest in environmental and land use matters. Subscribe and follow us to help advocate, negotiate, and when necessary, litigate to protect and restore the South Florida ecosystem."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /blog
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Taryn Barnett
    display_name: Taryn
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: taryneliana@gmail.com
    web: https://taryneliana.github.io/
    twitter: https://twitter.com/ElianaTaryn
    description: "Master's student with a demonstrated interest in Environmental Justice. Demonstrates knowledge and interest in cultural and intellectual property, digital anthropology, visual anthropology, and environmental anthropology—proficiency in designing digital assets for environmental campaigns through the Environmental Media Lab at the Abess Center at University of Miami."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
